version: '3.8'

services:
  gateway:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./config.yml:/etc/lightfile6/config.yml:ro
      - cache-data:/var/lib/lightfile6-insights-gateway
    environment:
      - LIGHTFILE6_AWS_REGION=${AWS_REGION:-ap-northeast-1}
      - LIGHTFILE6_AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - LIGHTFILE6_AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    restart: unless-stopped
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  cache-data:
  minio-data: